version: '3.8'

services:
  # Angular Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_BASE_URL=http://localhost:8080
    depends_on:
      - backend

  # PHP Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=lsdb_chatbot
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - CORS_ORIGIN=http://localhost:4200
    depends_on:
      - mysql

  # MySQL Database
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lsdb_chatbot
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  # PhpMyAdmin (for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword
    depends_on:
      - mysql

volumes:
  db_data: